// task
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace day5
{
        class Student
        {
            public String name;
            public int rollNo, marks;

        }
        class Program
        {
            static void Main(string[] args)
            {
                Student[] sa = new Student[2];
                for (int i = 0; i < sa.Length; i++)
                {
                    sa[i] = new Student();
                    Console.WriteLine("Enter student name: ");
                    sa[i].name = Console.ReadLine();
                    Console.WriteLine("Enter student roll no: ");
                    sa[i].rollNo = Convert.ToInt32(Console.ReadLine());
                    Console.WriteLine("Enter student marks: ");
                    sa[i].marks = Convert.ToInt32(Console.ReadLine());
                }
                Console.WriteLine("S.No\t Roll_NO \t Student Name\t\t Percentage\t\tGrades");
                Console.WriteLine();
                char grade;
                for (int i = 0; i < 2; i++)
                {
                    int totam = (sa[i].marks * 100) / 500;
                    if (totam >= 90 && totam <= 100)
                    {
                        grade = 'A';
                    }
                    else if (totam >= 80 && totam <= 89)
                        grade = 'B';
                    else if (totam >= 65 && totam <= 79)
                        grade = 'C';
                    else if (totam >= 55 && totam <= 64)
                        grade = 'D';
                    else if (totam >= 33 && totam <= 54)
                        grade = 'E';
                    else
                        grade = 'F';
                    Console.WriteLine((i + 1) + "\t\t" + sa[i].rollNo + "\t\t" + sa[i].name + "\t\t" + totam + "\t\t" + grade);
                    Console.WriteLine();

                }
                Console.ReadLine();
            }
        }
    }
}

// structers
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace day5
{
    public struct Student // structure declaration
    {
        public String name;
        public int rollNo, marks;

    }
    class Program
    {
        static void Main(string[] args)
        {
            Student s1;     // there is no need to write new to create new object of structure
            s1.name = "student";
            s1.rollNo = 1;
            s1.marks = 99;
            Console.WriteLine("name : " + s1.name + "\nroll no : " + s1.rollNo + "\nmarks : " + s1.marks);
            Console.ReadLine();
        }
    }
}


//enum
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace day5
{
class program
	{
    public enum Choiceenum // enum declaration
    {
        Addition,Subtraction,Multiplication,Divide
    }
    public static void Main()
    {
        Console.WriteLine("Enter two numbers");
        int Number1 = Convert.ToInt32(Console.ReadLine());
        int Number2 = Convert.ToInt32(Console.ReadLine());

        Console.WriteLine("Enter choice you want to perform");
        foreach (var item in Enum.GetValues(typeof(Choiceenum))) //loop is used to select choice
        {
            Console.WriteLine(((int)item) + " " + item);
        }
		
		
		//var arr = Enum.GetValues(typeof(Choiceenum)); // this loop also can be used which peroms same above function
        //for (int i = 0; i < arr.Length; i++)
        //{
        //    Console.WriteLine(arr.GetValue(i));
        //}


        int Choice = Convert.ToInt32(Console.ReadLine());
        switch (Choice)
        {
            case (int)Choiceenum.Addition:
                Console.WriteLine("Addition of two number is  :- {0}", (Number1 + Number2));
                break;
            case (int)Choiceenum.Multiplication:
                Console.WriteLine("Addition of two number is  :- {0}", (Number1 * Number2));
                break;
            case (int)Choiceenum.Subtraction:
                Console.WriteLine("Addition of two number is  :- {0}", (Number1 - Number2));
                break;
            case (int)Choiceenum.Divide:
                Console.WriteLine("Addition of two number is  :- {0}", (Number1 / Number2));
                break;
            default:
                Console.WriteLine("Please enter a valid Choice");
                break;
        }
        Console.ReadLine();
    }
}


//enum task
using System;
public struct Student
{
	public string name;
	public int rollno;
	public string gender;
}
	
public class student
{
	public enum Gender
	{
		female=0,male=1
	}

	public static void Main()
	{
		Student[] arr = new Student[2];
		arr[0].name="abc";
		arr[0].rollno=12;
		arr[1].name="def";
		arr[1].rollno=32;
			int c=0;
		for(int i=0;i<2;i++)
		{
			Console.WriteLine("enter gender for student: "+(i+1));
			Console.WriteLine("enter \n0.for female\n1.for male");
			c=Convert.ToInt32(Console.ReadLine());
			if(c==0)
			arr[i].gender=Gender.female.ToString();
			else if(c==1)
			arr[i].gender=Gender.male.ToString();	
		}
		Console.WriteLine("Name:\t\tRollNo\t\tGender");
		Console.WriteLine();
		for(int i=0;i<2;i++)
		{
			Console.WriteLine(arr[i].name+"\t\t\t"+arr[i].rollno+"\t\t\t"+arr[i].gender);
			Console.WriteLine();
			
		}
	
		
	}	

}



//exception handling
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace day5
{
    class program
    {
        public static void Main()
        {
            //int a = 5;
            //int c = a / 0;
            int[] arr = new int[2];
            try
            {
                Console.WriteLine(arr[2]);
                Console.WriteLine(c);
            }
            catch
            {
                Console.WriteLine("exception occurs");
            }
           
            Console.ReadLine();
        }
    }
}



// exception handling with stack trace
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace day5
{
    class program
    {
        public static void Main()
        {
            int[] arr = new int[2];
            try
            {
                Console.WriteLine(arr[2]);
             
            }
            catch(Exception ex)
            {
                Console.WriteLine("Exception occurs \n error : " + ex.Message + "\n stack trace :" + ex.StackTrace); // stack trace is used to show error line number
            }
            
           
            Console.ReadLine();
        }
    }
}


// exception handling for 2 exceptions
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace day5
{
    class program
    {
        public static void Main()
        {
            int a = 5;
            
            int[] arr = new int[2];
            try
            {
                int c = a / 0;
                Console.WriteLine(arr[2]);
             
            }
            catch(DivideByZeroException ex)
            {
                Console.WriteLine("Exception occurs in division \n error : " + ex.Message + "\n stack trace :" + ex.StackTrace); // stack trace is used to show error line number
            }
            catch(IndexOutOfRangeException ex)
            {
                Console.WriteLine("Exception occurs in array \n error : " + ex.Message + "\n stack trace :" + ex.StackTrace);
            }
           
            Console.ReadLine();
        }
    }
}

// exception handling with finally
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace day5
{
    class program
    {
        public static void Main()
        {
            int a = 5;
            
            int[] arr = new int[2];
            try
            {
             
                Console.WriteLine(arr[2]);
             
            }
            catch(Exception ex)
            {
                Console.WriteLine("Exception occurs in array \n error : " + ex.Message + "\n stack trace :" + ex.StackTrace);
            }
            finally
            {
                Console.WriteLine("This will be executed every time without prior to exception");
            }
           
            Console.ReadLine();
        }
    }
}


//user defined exception handling
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace day5
{
    public class TempIsZeroException : Exception
    {
        public TempIsZeroException(string message) : base(message)
        {
        }
    }
    public class Temperature
    {
        int temperature = 0;

        public void showTemp()
        {

            if (temperature == 0)
            {
                throw (new TempIsZeroException("Zero Temperature found")); // base messsage
            }
            else
            {
                Console.WriteLine("Temperature: {0}", temperature);
            }
        }
    }

    class TestTemperature
        {
            static void Main(string[] args)
            {
                Temperature temp = new Temperature();
                try
                {
                    temp.showTemp();
                }
                catch (TempIsZeroException e)
                {
                    Console.WriteLine("TempIsZeroException: {0}", e.Message); // string message
                }
                Console.ReadKey();
            }
        }
    }
   
   
   
//used defined exception handling-2
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace day5
{
    public class MyException : Exception
    {
        public MyException(string message) : base(message)
        {

        }
    }
    public class Fitness
    {
        int points = 0;
        public void ShowResult()
        {
            if (points < 110)
            {
                throw new MyException("Player failed the fitness test!");
            }
            else
            {
                throw new MyException("Player passed the fitness test!");
            }
        }
    }
    class Class6
    {
        public static void Main()
        {
            Fitness f = new Fitness();
            try
            {
                f.ShowResult();
            }
            catch (MyException e)
            {
                Console.WriteLine("User defined exceptions: {0}", e.Message);
            }
            Console.ReadLine();

        }


    }
}
   

